_target_: src.datamodules.mask_datamodule.MASKDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 32
train_val_test_split: [13_230, 1_890, 3_780]
num_workers: 0
pin_memory: False
