# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: recycle.yaml # choose the datamodule for evaluation
  - model: recycle.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: /opt/ml/detection/dataset

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: /opt/ml/baseline/level2-object-detection-level2-cv-19/logs/experiments/runs/recycle_test/2022-03-22_17-20-35/checkpoints/last.ckpt
